name: Java CI with Gradle

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    env:
      MAIL: 'b7531752@gmail.com'

    steps:
      - uses: actions/checkout@v3
      - name: imprimir variables
        run: | 
              echo 'EL CORREO ES: $MAIL'
      - name: Set up JDK 19
        uses: actions/setup-java@v3
        with:
          java-version: '19'
          distribution: 'temurin'

      - name: Ejecutar Tests
        run: |
            ./gradlew test --tests 'src/test/java/evovital/uniquindio/edu/co/EmailTest.java'